// swift-tools-version: 5.9

import PackageDescription

// Generated by .github/workflows/release.yml — built from SagerNet/sing-box v1.13.18
let package = Package(
  name: "Libbox",
  platforms: [.iOS(.v13)],
  products: [
    .library(name: "Libbox", targets: ["Libbox"]),
  ],
  targets: [
    .binaryTarget(
      name: "Libbox",
      url: "https://github.com/TangmaeTT/libbox-spm-bullios/releases/download/v1.13.18/Libbox.xcframework.zip",
      checksum: "6848d92a4f58ef7cb9cc4be445ec595e40c953ab29a3ad20af1ce10d4fb3928a"
    )
  ]
)
