// swift-tools-version: 5.9

import PackageDescription

// Generated by .github/workflows/release.yml — built from SagerNet/sing-box v1.13.18
let package = Package(
  name: "Libbox",
  platforms: [.iOS(.v13)],
  products: [
    .library(name: "Libbox", targets: ["Libbox"]),
  ],
  targets: [
    .binaryTarget(
      name: "Libbox",
      url: "https://github.com/TangmaeTT/libbox-spm-bullios/releases/download/v1.13.18-update1/Libbox.xcframework.zip",
      checksum: "eb2fc0da667dc32f5e9acce81fc9bff8631ee19c2d808a78b56c8f221ee2b9c5"
    )
  ]
)
