// swift-tools-version: 5.9

import PackageDescription

// Generated by .github/workflows/release.yml — built from SagerNet/sing-box v1.12.25
let package = Package(
  name: "Libbox",
  platforms: [.iOS(.v13)],
  products: [
    .library(name: "Libbox", targets: ["Libbox"]),
  ],
  targets: [
    .binaryTarget(
      name: "Libbox",
      url: "https://github.com/TangmaeTT/libbox-spm-bullios/releases/download/v.12.25/Libbox.xcframework.zip",
      checksum: "5eb7f03ad007b48eff6d885348e54a9e451dba7a41ccc01a9aa41e2a76a4926f"
    )
  ]
)
